security:
    providers:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
           dev:
              pattern: ^/(_(profiler|wdt)|css|images|js)/
              security: false

           paneladm:
              pattern:   ^/
              provider: sites
              anonymous: ~
              form_login:
                  login_path:   /login
                  check_path:   /login_check
                  post_only:    true
                  username_parameter:    _user
                  password_parameter:    _passwd
                  csrf_parameter:        _csrf_token

              logout:
                  path: logout
                  target: /

    access_control:
          - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/, roles: [ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_USER] }